name: Generate Plagiarism Reports
on:
  schedule:
    - cron: 0 0 * * * # Runs daily at midnight UTC
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  generate-plagiarism-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Get All "os-tues" GitHub Classrooms
        id: get_all_classrooms
        run: |
          # Get all classrooms using the GitHub CLI
          CLASSROOMS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /classrooms)

          # Filter out classrooms without "os-tues" in the name
          CLASSROOMS=$(echo "$CLASSROOMS" | jq '[.[] | select(.name | test("os-tues"))]')

          # Add $CLASSROOMS to workflow environment
          echo $CLASSROOMS
          echo CLASSROOMS=$CLASSROOMS >> $GITHUB_ENV

      - name: Get assignments for each classrooms
        id: get_assignments
        run: |
          # Get the IDs of all classrooms
          CLASSROOM_IDS=$(echo $CLASSROOMS | jq '.[] | .id')
          echo $CLASSROOM_IDS
          ASSIGNMENTS=[]

          # Get all assignments for each classroom
          echo "$CLASSROOM_IDS" | while read -r id; do
            CLASSROOM_ASSIGNMENTS=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /classrooms/$id/assignments)

            ASSIGNMENTS=$(echo "$ASSIGNMENTS" | jq --argjson new_assignments "$CLASSROOM_ASSIGNMENTS" '. + $new_assignments')
          done

          # Add $CLASSROOMS to workflow environment
          echo $ASSIGNMENTS
          echo ASSIGNMENTS=$ASSIGNMENTS >> $GITHUB_ENV
